### ISSUE TITLE
{Request/Issue] Another script and star/voting color.

### ISSUE THREAD

**Issue by DesolatePsyche** [Catgrills/Exhentai.usercss#3]
Hey,
First of all do you think you can make your style compatible with " https://sleazyfork.org/en/scripts/34422-unlock-hath-perks " ?

(i.e - menu doesn't show up well, stars/votes don't appear when hovering over. Only text hover shows up.)

And secondly, can you somehow make that  already voted galleries are applied on front page or in search. Right now already voted galleries are shown as unrated a.k.a same color. Makes it quite tedious to check whenever I have already read something or not. (thumbnail view)

Second way to explain it would be that in original theme. If you have rated something. For example given 4.5 stars it turns blue. And it's shown blue whenever you are on the gallery, on the front page, on favorites, in search mode. But with bamboo, ones I given star/vote are still golden/yellow.

**Comment by Catgrills** [comment]
Hey DesolatePsyche,

I updated the css. The hover doesn't work on the front page, but you can remove this line (line 829) 
``` css
.id4 {
    visibility: hidden;
}
```
to be able to see the original detail footer.

**Comment by DesolatePsyche** [comment]
Thank you :)
