### ISSUE TITLE
Torrent section is not showing.

### ISSUE THREAD

**Issue by ghost** [Catgrills/Exhentai.usercss#5]
Hi, is saw this section on the README sample, but in my case this part is not showing.
I see it if i go to the 3-line button then 'Torrent Download (x)' then an pop-up appears and then is showing.
I install all that is described in the readme but still not working.
![screenshot from 2018-11-16 16-21-46](https://user-images.githubusercontent.com/8683793/48642909-fb0f2f80-e9bc-11e8-828d-b473851cd2cb.png)
I need to change something in the settings or anything ?

**Comment by Catgrills** [comment]
I edited the Readme : you have to install <a href="https://sleazyfork.org/en/scripts/10968-sadpanda-torrent-inline">sadpanda torrent inline</a>

**Comment by ghost** [comment]
Great! is working perfectly.
Thanks and closing.
