### ISSUE TITLE
[INFO] Heads up, site got design update, so userstyle is broken at some places

### ISSUE THREAD

**Issue by DesolatePsyche** [Catgrills/Exhentai.usercss#7]
Couldn't find a way to message in github thus posted it in the issues.

Anyhow, since site got design update. Style broke down. Most noticeable part is that top bar is fairly borked.

**Comment by Catgrills** [comment]
Yeah, I noticed it. I'll post an update soon enough (not until this WE tho).

**Comment by Sazoji** [comment]
plz fix quickly, both borked bamboo and new design are painful

**Comment by Catgrills** [comment]
Just updated the script, enjoy.
