### ISSUE TITLE
eze has deprecated most of his features.

### ISSUE THREAD

**Issue by ghost** [Catgrills/Exhentai.usercss#8]
> eze Deprecation Notice
> The eze userscript is no longer undergoing active development. Several features have already stopped working, and more features are likely to break in the future.
> 
> Several features have already been converted to standalone userscripts that will be easier to maintain in the future:
> 
> Random gallery
> Gallery thumbnail loader
> Removed gallery info recovery
> Full title readability on search results
> These features can be found in the collection of userscripts at https://dnsev-h.github.io/x/.

The only one that I can see for the moment that don't work properly with Bamboo is x/full-title.

**Comment by Catgrills** [comment]
Thanks for the head up ! You can already see the full title by hovering the title with Bamboo, no need for full-title.
